### ISSUE TITLE
installing flask-restful

### ISSUE THREAD

**Issue by sposs** [mvantellingen/localshop#156]
Hi,
For some reason, localshop does not manage to get any valid version for the pip package flask-restful. 
```
fd8900de2ffed67$ pip install flask-restful
Collecting flask-restful
  DEPRECATION: Failed to find 'flask-restful' at http://myhost:7000/simple/flask-restful/. It is suggested to upgrade your index to support normalized names as the name in /simple/{name}.
  Could not find a version that satisfies the requirement flask-restful (from versions: )
  No matching distribution found for flask-restful
```
There is no such problem with flask-login for example...

**Comment by canassa** [comment]
Are you running the latest Localshop version?

You probably have a bogus package in your database, please try to remove the flask-restful package using the admin interface and try again.

**Comment by sposs** [comment]
I do not have any flask-restful in my localshop. I don't know if I have the last version.

**Comment by canassa** [comment]
You can check the localshop version with pip, e.g.:

```
pip freeze | grep -i localshop
````

The latest version is `0.9.2`

**Comment by sposs** [comment]
I have an old version: 0.6.0, which I patched to have the LDAP
authentication... As far as I last checked, this was not merged and there
was a problem with the django-ldap module version... It's still very
strange that it's the only package that has such issue...

Le mer. 20 mai 2015 à 16:56, Cesar Canassa <notifications@github.com> a
écrit :

**Comment by canassa** [comment]
0.6.0 is quite old, that version still uses the XMLRpc API instead of the newer JSON API. The PyPI XMLRpc API is know to give some timeouts and return bogus results for some packages.

You should consider upgrading to the latest version, just be aware that if you use SQLite as a database, you will need to migrate to MySQL or PostgreSQL. If you do that, please resubmit your patch so that we can merge it.
