### ISSUE TITLE
SIP package not cached

### ISSUE THREAD

**Issue by MrRagga-** [mvantellingen/localshop#58]
Hi,
is it possible to cache packages such as SIP (same for  PyQT) https://pypi.python.org/simple/SIP/. 
The problem that localshop does not cache SIP is due to SIP on pypi just holds a reference to the download url's of the package instead of supporting direct downloads.

Is there any workaround for packages like this to get it cached by localshop?

Regards, 

Jonas

**Comment by canassa** [comment]
PyQT and SIP are not compatible with `pip`. Since Qt is a more complicated system with a compiled C++ codebase underlying the python interface it provides you, it can be more complex to install than just a pure python code package that pip works best with, so grabbing the installers can be far easier.

I think that PyQT was even removed from PyPI, probably due to [PEP 438](https://www.python.org/dev/peps/pep-0438/)

```
pip install pyqt4
Collecting pyqt4
  Could not find any downloads that satisfy the requirement pyqt4
  No distributions at all found for pyqt4
```

PIP can still found SIP, but you have to pass the `--allow-external` and `--allow-insecure` flags. But the build is broken:

```
pip install SIP --allow-external SIP --allow-unverified SIP
Collecting SIP
  SIP is potentially insecure and unverifiable.
  Downloading http://sourceforge.net/projects/pyqt/files/sip/sip-4.16.5/sip-4.16.5.zip (982kB)
    100% |################################| 983kB 2.4MB/s 
    Traceback (most recent call last):
      File "<string>", line 18, in <module>
    IOError: [Errno 2] No such file or directory: '/tmp/pip-build-6w2j9l/SIP/setup.py'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
    
      File "<string>", line 18, in <module>
    
    IOError: [Errno 2] No such file or directory: '/tmp/pip-build-6w2j9l/SIP/setup.py'
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-6w2j9l/SIP

```

I don't that there is nothing that can be done in localshop to fix this. This is a package maintainer issue.
