### ISSUE TITLE
localshop fails to install on Python 3.x

### ISSUE THREAD

**Issue by thedrow** [mvantellingen/localshop#74]
Due to the fact that the latest released version uses Pillow<2.0.0 the installation fails.
If installed from source the installation fails due to django-userna.

**Comment by canassa** [comment]
Eventlet is still not Python 3 compatible.

Anyway. I don't think that localshop **really** needs an async worker like Eventlet. Our workers are quite simple and they should not require this extra layer of complexity.

Django-storages is also an issue. It is not Python 3 compatible is that's mainly because boto is not Python 3 compatible.

**Comment by mvantellingen** [comment]
I've implemented basic support for python 3 in #154 

Only making sure that all tests pass for now

**Comment by mvantellingen** [comment]
@canassa if we fix #143 then this should be done right?

**Comment by canassa** [comment]
Right :+1:
